#!/bin/sh

set -e
umask 0002

OPTIONS="--show - --polar disabled --relation-base /etc/device/services/app/tika2 --relation-name name --relation-suffix .txt --relation tika2"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

