#!/bin/bash

#
# 389 Directory Server Postdiscovery - dovecot user
# =================================================
#
# This script adds dovecot user to instances.

set -e

request="${1}"
instance="${2}"

uris="ldapi://%2frun%2fslapd-${instance}.socket"


#
# Autogenerate the dovecot user
# -----------------------------
#
# If the LDAP server is local, we need to create the dovecot user in
# LDAP so autobind works.

logger -t "${0}" "Notice: Adding dovecot user on instance '${instance}'..."

dsidm -b "cn=config" ${uris} organizationalunit create --ou people >/dev/null || /bin/true

dsidm -b "cn=config" ${uris} user create --uid dovecot --cn dovecot --displayName "Dovecot Server" --uidNumber `id -u dovecot` --gidNumber `id -g dovecot` --homeDirectory "`echo ~dovecot`" >/dev/null || /bin/true

aci='(targetattr != "userPassword")(version 3.0;acl "Dovecot Daemon";allow (read,search,compare) (userdn = "ldap:///uid=dovecot,ou=people,cn=config");)'

logger -t "${0}" "Notice: attempting to add dovecot aci on instance '${instance}'..."
logger -t "${0}" "Notice: dovecot aci: ${aci}"

find /etc/device/services/ldap/suffix/ -mindepth 1 -maxdepth 1 -type l | \
while read line; do

  target=$(readlink -f "$line")

  if test ! -f "$line/suffix.txt"; then
    continue;
  fi
  suffix="$(head -n 1 $line/suffix.txt)"

  if [ ! -e "$line/instance.d/name.txt" ]; then
    continue;
  fi
  if [ "${instance}" != "$(head -n 1 $line/instance.d/name.txt)" ]; then
    continue;
  fi

  existing=$(ldapsearch -H ${uris} -Y EXTERNAL -b "${suffix}" -o ldif-wrap=no -s base "(aci=*)" aci | grep "ldap:///uid=dovecot,ou=people,cn=config" || /bin/true)

  if [ -z "${existing}" ]; then

    ldapmodify -H ${uris} -Y EXTERNAL -c <<- EOF || true
dn: ${suffix}
changetype: modify
add: aci
aci: ${aci}

EOF

  else

    ldapmodify -H ${uris} -Y EXTERNAL -c <<- EOF || true
dn: ${suffix}
changetype: modify
delete: aci
${existing}
-
add: aci
aci: ${aci}

EOF

  fi

done

logger -t "${0}" "Notice: Added dovecot user to local LDAP instance '${instance}'."


