#!/bin/sh

set -e
umask 0002

OPTIONS="--show - --polar disabled --integer-minimum 1 --integer-maximum=1000000 --integer max-userip-connections"

if [ "$1" == "--" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set ${OPTIONS} "$@"

fi

