#!/bin/bash

#
# Dovecot Autodiscovery - Sieve Compile
# =====================================
#
# This script compiles sieves for a dovecot server.

set -e
umask 0022

logger -t "${0}" "Notice: Compiling sieve scripts..."

/usr/bin/sievec /var/lib/dovecot-pigeonhole/junk.sieve
/usr/bin/sievec /var/lib/dovecot-pigeonhole/vacation.sieve
/usr/bin/sievec /var/lib/dovecot-pigeonhole/report-ham.sieve
/usr/bin/sievec /var/lib/dovecot-pigeonhole/report-spam.sieve


