#!/bin/bash
  
#
# Dovecot Autodiscovery - Sieve IMAP
# ==================================
# 
# This script autogenerates the sieve imap configuration for a dovecot server.

set -e
umask 0022

myhostname=$(cat /etc/hostname)

logger -t "${0}" "Notice: Adding sieve to dovecot 20-imap.conf..."

cat >> "20-imap.conf" <<- EOF

protocol imap {
  # Space separated list of plugins to load (default is global mail_plugins).
  mail_plugins = \$mail_plugins imap_sieve

  # Maximum number of IMAP connections allowed for a user from each IP address.
  # NOTE: The username is compared case-sensitively.
  #mail_max_userip_connections = 10
}

EOF

