#!/bin/sh
  
set -e
umask 0002

if [ "$1" == "--" ]; then

#  /usr/bin/sudo /usr/bin/systemctl --quiet disable dovecot.service

  if test -f "disabled.bin"; then
    echo "submission is already disabled."
  else
    touch "disabled.bin"
    if systemctl is-active --quiet dovecot-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl restart dovecot-autodiscovery.service
      /usr/bin/sudo /usr/bin/systemctl restart dovecot.service
    else
      echo "submission will be disabled on next reboot."
    fi
  fi

fi

